### ISSUE TITLE
Digital Navigation System at the college entrance

### ISSUE THREAD

**Issue by hridyakrishna** [amfoss/Hack4Amrita#8] opened 2019-04-21 08:42 UTC
**What is the issue that you are facing?**
The current map at the entrance of the college is difficult to be figured out. People, especially parents, find it difficult to locate certain rooms and halls in the college, such as Campus director's office, Principal's office, Counsellor's department etc.  

**How often do you face this issue?**
It is faced when people are new to the college, mainly the parents or relatives of students, visiting for the first time. It is mainly difficult during the class hours when there are less students and staffs nearby.

**Where do you face this issue?**
It is faced at the college entrance when people gets confused with the directions.

**Do you think, a lot of your friends face the same issue?**
Yes, I think many people have faced this issue.

**What have you tried to solve the issue?**
I have not tried anything to solve this issue.

**What do you think is causing the issue?**
Lack of proper navigation in the complex structure of current map.

**Have you thought of any ideas that may solve the issue?**
There can be a navigation system at the entrance of the college. The destination can be selected from the options provided and the route to the location can be displayed digitally.

- [x] By submitting this issue, I acknowledge that this follows the [code of conduct](CODE_OF_CONDUCT.md) of Hack4Amrita.

**Comment by vibhoothiiaanand** [comment] 2019-04-27 12:00
Possible Duplicate of #6

**Closed by vibhoothiiaanand** 2019-04-27 12:00 UTC
